version: "3"
services: 
  nginx:
    ports:
      - "8080:80"
    image: nginx:stable
    volumes: 
      - "./default.conf:/etc/nginx/conf.d/default.conf"
    networks:
      - frontend

  nginx-exporter:
    image: nginx/nginx-prometheus-exporter:0.4.2
    container_name: nginx-exporter
    restart: unless-stopped
    environment:
      - SCRAPE_URI=http://nginx/nginx_status
      - TELEMETRY_PATH=/metrics
      - NGINX_RETRIES=10
    ports:
      - "9113:9113"
    networks:
      - frontend
    logging:
      driver: "json-file"
      options:
        max-size: "5m"
  
  prometheus:
    image: prom/prometheus:v2.21.0
    container_name: prometheus
    ports:
      - "9000:9090"
    networks:
      - frontend
    volumes:
      - "./prometheus.yml:/etc/prometheus/prometheus.yml"
      - "./targets-nginx-exporter.yml:/etc/prometheus/sd/targets-nginx-exporter.yml"

networks:
  frontend:
