version: "3"
services: 
  nginx:
    ports:
      - "8080:80"
    image: nginx:stable
    volumes: 
      - "./default.conf:/etc/nginx/conf.d/default.conf"
    networks:
      - frontend

  nginx-exporter:
    image: nginx/nginx-prometheus-exporter:0.4.2
    container_name: nginx-exporter
    restart: unless-stopped
    environment:
      - SCRAPE_URI=http://nginx/nginx_status
      - TELEMETRY_PATH=/metrics
      - NGINX_RETRIES=10
    ports:
      - "9113:9113"
    networks:
      - frontend
    logging:
      driver: "json-file"
      options:
        max-size: "5m"

networks:
  frontend:
