all:
  hosts:
  children:
    servers_group:
      hosts:
        server_one:
          ansible_ssh_user: user
          ansible_sudo_pass: 123
        server_two:
          ansible_ssh_user: user
          ansible_sudo_pass: 123
