---
- hosts: server_one
  become: true
  tasks:
    - name: Create directory
      file:
        path: /tmp/example_dir
        state: directory
        owner: root
        group: root
    - name: install htop
      apt:
        name: htop
        state: present
        update_cache: true
    - name: install tmux
      apt:
        name: tmux
        state: present
        update_cache: true